-- ============================================================
-- Run this in Supabase SQL Editor to set up your database
-- ============================================================

-- NOTE: Copy and paste the SECTION for user_notes only
-- into the SQL Editor if you already ran the full schema before.

-- 1. PROFILES
create table if not exists profiles (
  id uuid references auth.users on delete cascade primary key,
  name text default '',
  username text,
  bio text default '',
  avatar_url text default '',
  instagram text default '',
  twitter text default '',
  github text default '',
  website text default '',
  onboarding_completed boolean not null default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
alter table profiles add column if not exists onboarding_completed boolean not null default false;
alter table profiles add column if not exists role text not null default 'user';
create unique index if not exists idx_profiles_username on profiles(username) where username is not null;

-- 2. STUDY SESSIONS (daily minutes)
create table if not exists study_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  date date not null,
  minutes integer not null default 0,
  created_at timestamptz default now(),
  unique (user_id, date)
);
create index if not exists idx_study_sessions_user on study_sessions(user_id);

-- 3. QUIZ SCORES
create table if not exists quiz_scores (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  date timestamptz not null,
  score integer not null,
  total integer not null,
  net_score integer not null,
  created_at timestamptz default now(),
  unique (user_id, date)
);
create index if not exists idx_quiz_scores_user on quiz_scores(user_id);

-- 4. TEST SCORES
create table if not exists test_scores (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  date timestamptz not null,
  score integer not null,
  total integer not null,
  chapter text not null,
  created_at timestamptz default now(),
  unique (user_id, date, chapter)
);
create index if not exists idx_test_scores_user on test_scores(user_id);

-- 5. ACTIVITY SNAPSHOTS
create table if not exists activity_snapshots (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  timestamp text not null,
  type text not null,
  score integer,
  total integer,
  label text,
  items jsonb default '[]',
  created_at timestamptz default now(),
  unique (user_id, timestamp, type)
);
create index if not exists idx_activity_user on activity_snapshots(user_id);

-- 6. TOPIC ACCURACY
create table if not exists topic_accuracy (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  topic text not null,
  correct integer not null default 0,
  total integer not null default 0,
  updated_at timestamptz default now(),
  unique (user_id, topic)
);
create index if not exists idx_topic_accuracy_user on topic_accuracy(user_id);

-- 7. WEAK AREAS
create table if not exists weak_areas (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  topic text not null,
  accuracy numeric(5,2) not null,
  chapter text,
  type text default 'topic',
  created_at timestamptz default now()
);
create index if not exists idx_weak_areas_user on weak_areas(user_id);

-- 8. CHAPTER PROGRESS
create table if not exists chapter_progress (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  chapter text not null,
  subject text not null,
  completed_topics integer default 0,
  total_topics integer default 0,
  questions_attempted integer default 0,
  questions_correct integer default 0,
  flashcards_reviewed integer default 0,
  flashcards_mastered integer default 0,
  last_studied_at timestamptz,
  unique (user_id, chapter, subject)
);
create index if not exists idx_chapter_progress_user on chapter_progress(user_id);

-- 9. USER POINTS (for leaderboard)
create table if not exists user_points (
  user_id uuid references auth.users on delete cascade primary key,
  points integer not null default 0,
  updated_at timestamptz default now()
);

-- 10. USER NOTES (private per-user vault storage)
-- Each note preserves the file path + content so the parser/layout works unchanged.
create table if not exists user_notes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  chapter text not null,
  subject text not null default '',
  path text not null,
  title text not null,
  content text not null,
  content_hash text,
  canonical_slug text,
  tags text[] default '{}',
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (user_id, path)
);
alter table user_notes add column if not exists content_hash text;
alter table user_notes add column if not exists canonical_slug text;
alter table user_notes add column if not exists author text not null default '';
create index if not exists idx_user_notes_user on user_notes(user_id);
create unique index if not exists idx_user_notes_user_content_hash on user_notes(user_id, content_hash) where content_hash is not null;
create index if not exists idx_user_notes_canonical_slug on user_notes(user_id, canonical_slug);

-- 11. CHAT MESSAGES (AI Tutor conversations)
create table if not exists chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  session_id uuid not null,
  client_id text,
  role text not null,
  content text not null,
  created_at timestamptz default now()
);
alter table chat_messages add column if not exists client_id text;
create index if not exists idx_chat_messages_session on chat_messages(user_id, session_id);
create unique index if not exists idx_chat_messages_client_id on chat_messages(user_id, session_id, client_id) where client_id is not null;

-- 11A. CHAT SESSIONS (scoped AI memory roots)
create table if not exists chat_sessions (
  id uuid primary key,
  user_id uuid references auth.users on delete cascade not null,
  type text not null default 'concept_discussion',
  title text not null default 'New Chat',
  subject text,
  chapter text,
  scope jsonb not null default '{}',
  summary text default '',
  last_message_at timestamptz default now(),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
create index if not exists idx_chat_sessions_user on chat_sessions(user_id, updated_at desc);
create index if not exists idx_chat_sessions_scope on chat_sessions using gin(scope);

-- 11B. CHAT CONTEXT SUMMARIES (compressed conversation memory)
create table if not exists chat_context_summaries (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  session_id uuid references chat_sessions(id) on delete cascade not null,
  summary text not null,
  covered_message_ids bigint[] default '{}',
  token_estimate integer default 0,
  created_at timestamptz default now()
);
create index if not exists idx_chat_context_summaries_session on chat_context_summaries(user_id, session_id, created_at desc);

-- 11C. INTERACTION MEMORY (retrievable scoped memories)
create table if not exists interaction_memory (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  session_id uuid references chat_sessions(id) on delete cascade,
  memory_type text not null,
  subject text,
  chapter text,
  content text not null,
  metadata jsonb not null default '{}',
  content_hash text not null,
  created_at timestamptz default now(),
  unique (user_id, content_hash)
);
create index if not exists idx_interaction_memory_scope on interaction_memory(user_id, memory_type, subject, chapter);

-- 13. STUDENT COGNITIVE STATE TABLES
create table if not exists student_learning_state (
  user_id uuid references auth.users on delete cascade primary key,
  mastery_map jsonb not null default '{}',
  weak_topics jsonb not null default '[]',
  confidence_levels jsonb not null default '{}',
  misconception_patterns jsonb not null default '[]',
  recent_failures jsonb not null default '[]',
  learning_velocity jsonb not null default '{}',
  focus_topics jsonb not null default '[]',
  recovery_queue jsonb not null default '[]',
  forgetting_curve_state jsonb not null default '{}',
  solved_question_embeddings jsonb not null default '[]',
  concept_relationships jsonb not null default '[]',
  exam_goals jsonb not null default '[]',
  preferred_difficulty text not null default 'adaptive',
  tutor_personality_prompt text not null default '',
  generated_learning_profile text not null default '',
  adaptive_recommendations jsonb not null default '[]',
  streak_data jsonb not null default '{}',
  study_patterns jsonb not null default '{}',
  performance_trends jsonb not null default '{}',
  updated_at timestamptz default now()
);
alter table student_learning_state add column if not exists misconception_patterns jsonb not null default '[]';
alter table student_learning_state add column if not exists solved_question_embeddings jsonb not null default '[]';
alter table student_learning_state add column if not exists concept_relationships jsonb not null default '[]';
alter table student_learning_state add column if not exists exam_goals jsonb not null default '[]';
alter table student_learning_state add column if not exists preferred_difficulty text not null default 'adaptive';
alter table student_learning_state add column if not exists tutor_personality_prompt text not null default '';
alter table student_learning_state add column if not exists generated_learning_profile text not null default '';

create table if not exists student_mastery (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  concept_slug text not null,
  mastery numeric(5,2) not null default 0,
  confidence numeric(5,2) not null default 0,
  evidence jsonb not null default '[]',
  updated_at timestamptz default now(),
  unique (user_id, concept_slug)
);
create index if not exists idx_student_mastery_user on student_mastery(user_id);

create table if not exists student_misconceptions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  concept_slug text not null,
  pattern text not null,
  severity text not null default 'medium',
  evidence jsonb not null default '[]',
  last_seen_at timestamptz default now(),
  created_at timestamptz default now()
);
create index if not exists idx_student_misconceptions_user on student_misconceptions(user_id, concept_slug);

create table if not exists student_focus_queue (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  concept_slug text not null,
  priority integer not null default 0,
  reason text default '',
  due_at timestamptz,
  status text not null default 'pending',
  created_at timestamptz default now()
);
create index if not exists idx_student_focus_queue_user on student_focus_queue(user_id, status, priority desc);

create table if not exists student_recovery_tasks (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  concept_slug text,
  task text not null,
  source text not null default 'ai_evaluation',
  status text not null default 'pending',
  due_at timestamptz,
  metadata jsonb not null default '{}',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
create index if not exists idx_student_recovery_tasks_user on student_recovery_tasks(user_id, status, due_at);

create table if not exists student_ai_profiles (
  user_id uuid references auth.users on delete cascade primary key,
  tutor_personality_prompt text not null default '',
  generated_learning_profile text not null default '',
  adaptive_strategy text not null default '',
  updated_at timestamptz default now()
);

create table if not exists student_goal_profiles (
  user_id uuid references auth.users on delete cascade primary key,
  exam_goals jsonb not null default '[]',
  preferred_difficulty text not null default 'Moderate',
  survey jsonb not null default '{}',
  updated_at timestamptz default now()
);

-- 14. CANONICAL VAULT AND RETRIEVAL TABLES
create table if not exists vault_documents (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade,
  source_path text not null,
  subject text,
  chapter text,
  title text not null,
  content_hash text not null,
  canonical_slug text not null,
  metadata jsonb not null default '{}',
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (content_hash)
);
create index if not exists idx_vault_documents_user on vault_documents(user_id);
create index if not exists idx_vault_documents_slug on vault_documents(canonical_slug);

create table if not exists vault_chunks (
  id bigint generated by default as identity primary key,
  document_id bigint references vault_documents(id) on delete cascade not null,
  user_id uuid references auth.users on delete cascade,
  chunk_index integer not null,
  content text not null,
  content_hash text not null,
  token_estimate integer default 0,
  metadata jsonb not null default '{}',
  created_at timestamptz default now(),
  unique (document_id, chunk_index),
  unique (content_hash)
);
create index if not exists idx_vault_chunks_document on vault_chunks(document_id);
create index if not exists idx_vault_chunks_user on vault_chunks(user_id);

create table if not exists vault_nodes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade,
  canonical_slug text not null,
  label text not null,
  node_type text not null default 'concept',
  metadata jsonb not null default '{}',
  created_at timestamptz default now(),
  unique (user_id, canonical_slug)
);
create index if not exists idx_vault_nodes_slug on vault_nodes(canonical_slug);

create table if not exists vault_edges (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade,
  from_slug text not null,
  to_slug text not null,
  relation text not null,
  weight numeric(6,3) default 1,
  evidence jsonb not null default '[]',
  created_at timestamptz default now(),
  unique (user_id, from_slug, to_slug, relation)
);
create index if not exists idx_vault_edges_from on vault_edges(user_id, from_slug);
create index if not exists idx_vault_edges_to on vault_edges(user_id, to_slug);

create table if not exists vault_ingestion_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade,
  source text not null,
  content_hash text,
  status text not null,
  message text default '',
  metadata jsonb not null default '{}',
  created_at timestamptz default now()
);
create index if not exists idx_vault_ingestion_logs_user on vault_ingestion_logs(user_id, created_at desc);

create table if not exists content_embeddings (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade,
  document_id bigint references vault_documents(id) on delete cascade,
  chunk_id bigint references vault_chunks(id) on delete cascade,
  content_hash text not null,
  embedding jsonb not null,
  model text not null,
  metadata jsonb not null default '{}',
  created_at timestamptz default now(),
  unique (content_hash, model)
);
create index if not exists idx_content_embeddings_user on content_embeddings(user_id);

create table if not exists question_embeddings (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade,
  question_id text not null,
  content_hash text not null,
  embedding jsonb not null,
  model text not null,
  metadata jsonb not null default '{}',
  created_at timestamptz default now(),
  unique (content_hash, model)
);
create index if not exists idx_question_embeddings_user on question_embeddings(user_id);

create table if not exists concept_relationships (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade,
  from_slug text not null,
  to_slug text not null,
  relation text not null,
  evidence jsonb not null default '[]',
  created_at timestamptz default now(),
  unique (user_id, from_slug, to_slug, relation)
);
create index if not exists idx_concept_relationships_from on concept_relationships(user_id, from_slug);

create table if not exists semantic_clusters (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade,
  cluster_slug text not null,
  label text not null,
  concept_slugs text[] not null default '{}',
  metadata jsonb not null default '{}',
  created_at timestamptz default now(),
  unique (user_id, cluster_slug)
);

-- 15. EVALUATION AND ANALYTICS TABLES
create table if not exists daily_learning_metrics (
  user_id uuid references auth.users on delete cascade not null,
  date date not null,
  attempts integer not null default 0,
  correct integer not null default 0,
  minutes integer not null default 0,
  points integer not null default 0,
  metadata jsonb not null default '{}',
  updated_at timestamptz default now(),
  primary key (user_id, date)
);

create table if not exists attempt_analytics (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  surface text not null,
  question_id text,
  concept_slug text,
  topic text,
  chapter text,
  subject text,
  correct boolean not null default false,
  score numeric(8,2),
  max_score numeric(8,2),
  feedback text default '',
  misconception text default '',
  metadata jsonb not null default '{}',
  created_at timestamptz default now()
);
create index if not exists idx_attempt_analytics_user on attempt_analytics(user_id, created_at desc);
create index if not exists idx_attempt_analytics_topic on attempt_analytics(user_id, topic, created_at desc);

create table if not exists topic_velocity (
  user_id uuid references auth.users on delete cascade not null,
  topic text not null,
  chapter text,
  attempts integer not null default 0,
  correct integer not null default 0,
  last_accuracy numeric(5,2) not null default 0,
  velocity numeric(8,4) not null default 0,
  updated_at timestamptz default now(),
  primary key (user_id, topic)
);

create table if not exists performance_trends (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  metric text not null,
  scope text not null default 'global',
  value numeric(10,4) not null default 0,
  metadata jsonb not null default '{}',
  created_at timestamptz default now()
);
create index if not exists idx_performance_trends_user on performance_trends(user_id, metric, created_at desc);

create table if not exists attention_patterns (
  user_id uuid references auth.users on delete cascade not null,
  date date not null,
  context text not null default 'global',
  switches integer not null default 0,
  time_spent_seconds integer not null default 0,
  metadata jsonb not null default '{}',
  updated_at timestamptz default now(),
  primary key (user_id, date, context)
);

-- 12. STUDY STREAKS
create table if not exists study_streaks (
  user_id uuid references auth.users on delete cascade primary key,
  current_streak integer not null default 0,
  longest_streak integer not null default 0,
  last_study_date date,
  updated_at timestamptz default now()
);

-- 16. MD BANK (admin-uploaded .md files for note generator)
create table if not exists md_bank (
  id bigint generated by default as identity primary key,
  title text not null,
  author text not null default '',
  subject text not null default '',
  chapter text not null default '',
  tags text[] default '{}',
  content text not null,
  filename text not null,
  description text default '',
  created_by uuid references auth.users on delete set null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
alter table md_bank add column if not exists author text not null default '';
create unique index if not exists idx_md_bank_filename on md_bank(filename);
create index if not exists idx_md_bank_subject on md_bank(subject);
create index if not exists idx_md_bank_author on md_bank(author);
create index if not exists idx_md_bank_chapter on md_bank(chapter);
create index if not exists idx_md_bank_tags on md_bank using gin(tags);

-- 17. STUDY STATE SNAPSHOTS (full state JSON blob for cross-device sync)
-- Stores the complete StudyState so ALL non-synced fields (questionAttempts,
-- activityLog, aiTodos, reviewedFlashcards, masteredFlashcards, strongAreas,
-- achievements, subjectAccuracy, predictedWeakness, aiConversations) are
-- preserved between devices. The snapshot supplements the per-table data.
create table if not exists study_state_snapshots (
  user_id uuid references auth.users on delete cascade primary key,
  data jsonb not null default '{}',
  updated_at timestamptz default now()
);

-- ============================================================
-- RLS POLICIES
-- ============================================================
alter table study_state_snapshots enable row level security;

alter table profiles enable row level security;
alter table study_sessions enable row level security;
alter table quiz_scores enable row level security;
alter table test_scores enable row level security;
alter table activity_snapshots enable row level security;
alter table topic_accuracy enable row level security;
alter table weak_areas enable row level security;
alter table chapter_progress enable row level security;
alter table user_points enable row level security;
alter table user_notes enable row level security;
alter table chat_messages enable row level security;
alter table study_streaks enable row level security;
alter table chat_sessions enable row level security;
alter table chat_context_summaries enable row level security;
alter table interaction_memory enable row level security;
alter table student_learning_state enable row level security;
alter table student_mastery enable row level security;
alter table student_misconceptions enable row level security;
alter table student_focus_queue enable row level security;
alter table student_recovery_tasks enable row level security;
alter table student_ai_profiles enable row level security;
alter table student_goal_profiles enable row level security;
alter table vault_documents enable row level security;
alter table vault_chunks enable row level security;
alter table vault_nodes enable row level security;
alter table vault_edges enable row level security;
alter table vault_ingestion_logs enable row level security;
alter table content_embeddings enable row level security;
alter table question_embeddings enable row level security;
alter table concept_relationships enable row level security;
alter table semantic_clusters enable row level security;
alter table md_bank enable row level security;
alter table daily_learning_metrics enable row level security;
alter table attempt_analytics enable row level security;
alter table topic_velocity enable row level security;
alter table performance_trends enable row level security;
alter table attention_patterns enable row level security;

-- All tables: users can only access their own data
drop policy if exists "Own data only" on study_state_snapshots;
create policy "Own data only" on study_state_snapshots for all using (auth.uid() = user_id);

drop policy if exists "Own data only" on profiles;
create policy "Own data only" on profiles for all using (auth.uid() = id);
drop policy if exists "Own data only" on study_sessions;
create policy "Own data only" on study_sessions for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on quiz_scores;
create policy "Own data only" on quiz_scores for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on test_scores;
create policy "Own data only" on test_scores for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on activity_snapshots;
create policy "Own data only" on activity_snapshots for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on topic_accuracy;
create policy "Own data only" on topic_accuracy for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on weak_areas;
create policy "Own data only" on weak_areas for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on chapter_progress;
create policy "Own data only" on chapter_progress for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on user_points;
create policy "Own data only" on user_points for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on user_notes;
create policy "Own data only" on user_notes for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on chat_messages;
create policy "Own data only" on chat_messages for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on study_streaks;
create policy "Own data only" on study_streaks for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on chat_sessions;
create policy "Own data only" on chat_sessions for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on chat_context_summaries;
create policy "Own data only" on chat_context_summaries for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on interaction_memory;
create policy "Own data only" on interaction_memory for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on student_learning_state;
create policy "Own data only" on student_learning_state for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on student_mastery;
create policy "Own data only" on student_mastery for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on student_misconceptions;
create policy "Own data only" on student_misconceptions for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on student_focus_queue;
create policy "Own data only" on student_focus_queue for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on student_recovery_tasks;
create policy "Own data only" on student_recovery_tasks for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on student_ai_profiles;
create policy "Own data only" on student_ai_profiles for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on student_goal_profiles;
create policy "Own data only" on student_goal_profiles for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on vault_documents;
create policy "Own data only" on vault_documents for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on vault_chunks;
create policy "Own data only" on vault_chunks for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on vault_nodes;
create policy "Own data only" on vault_nodes for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on vault_edges;
create policy "Own data only" on vault_edges for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on vault_ingestion_logs;
create policy "Own data only" on vault_ingestion_logs for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on content_embeddings;
create policy "Own data only" on content_embeddings for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on question_embeddings;
create policy "Own data only" on question_embeddings for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on concept_relationships;
create policy "Own data only" on concept_relationships for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on semantic_clusters;
create policy "Own data only" on semantic_clusters for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on daily_learning_metrics;
create policy "Own data only" on daily_learning_metrics for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on attempt_analytics;
create policy "Own data only" on attempt_analytics for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on topic_velocity;
create policy "Own data only" on topic_velocity for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on performance_trends;
create policy "Own data only" on performance_trends for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on attention_patterns;
create policy "Own data only" on attention_patterns for all using (auth.uid() = user_id);

-- md_bank: all authenticated users can read, only admins can write
drop policy if exists "All authenticated can read md_bank" on md_bank;
create policy "All authenticated can read md_bank" on md_bank for select using (auth.role() = 'authenticated');
drop policy if exists "Admins can insert md_bank" on md_bank;
create policy "Admins can insert md_bank" on md_bank for insert with check (
  exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);
drop policy if exists "Admins can update md_bank" on md_bank;
create policy "Admins can update md_bank" on md_bank for update using (
  exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);
drop policy if exists "Admins can delete md_bank" on md_bank;
create policy "Admins can delete md_bank" on md_bank for delete using (
  exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);

-- Public can read usernames and points for leaderboard
drop policy if exists "Public read leaderboard" on profiles;
create policy "Public read leaderboard" on profiles for select using (true);
drop policy if exists "Public read points" on user_points;
create policy "Public read points" on user_points for select using (true);
-- ============================================================
-- Migration 006: Vault Bank â€” admin publishes chapter vaults to aclose users
-- Run this in Supabase SQL Editor after migration 005
--   (extends existing user_notes table; no new tables needed)
--
-- Model:
--   Admin uses the Note Agent to generate a full chapter vault
--   (notes + questions + mcqs + flashcards + quizzes + revision).
--   Admin can then "Publish to Vault Bank" â€” a single click that
--   flips shared_to_aclose = true on every user_notes row for that
--   chapter owned by admin.
--   aclose-role users see published chapter packages in the Vault
--   Bank tab inside the Note Agent. They click "Save to vault" to
--   copy the entire chapter (all files, paths preserved) into their
--   own user_notes table, so it appears in their Reader/Questions/etc.
--
-- Roles:
--   admin   â€” publishes/unpublishes their own chapter vaults
--   aclose  â€” browses Vault Bank, saves chapters to their own vault
--   user    â€” no Vault Bank access
-- ============================================================

-- Add the share flag
alter table user_notes
  add column if not exists shared_to_aclose boolean not null default false;

-- Track when the share flag was set (useful for "published N days ago")
alter table user_notes
  add column if not exists shared_at timestamptz;

-- Index for fast filtering when listing published chapters
create index if not exists idx_user_notes_shared
  on user_notes (user_id, chapter)
  where shared_to_aclose = true;

-- ============================================================
-- RLS POLICIES for Vault Bank
-- ============================================================

-- Helper: identify the single admin whose vaults are publishable.
-- In a multi-admin world this would be a per-publisher table; for
-- this app there is exactly one admin, so we hard-code the lookup
-- by joining profiles.role = 'admin'. Any user with role = 'admin'
-- can publish their own chapters. aclose users can only read rows
-- where shared_to_aclose = true. The publish endpoint is admin-only.
--
-- Existing "Own data only" policy on user_notes remains in force â€”
-- aclose users cannot UPDATE or DELETE admin rows; they can only
-- INSERT new rows of their own (covered by the existing insert policy
-- via with check (auth.uid() = user_id)).

-- Drop the old "Own data only" policy to add a more granular one
drop policy if exists "Own data only" on user_notes;

-- SELECT: a user can see (a) their own rows AND (b) any row marked
-- shared_to_aclose. Admins can also see any row they own (already
-- covered by (a)).
create policy "Own or shared via vault bank"
  on user_notes for select
  using (
    auth.uid() = user_id
    or (
      shared_to_aclose = true
      and exists (
        select 1 from profiles p
        where p.id = user_notes.user_id
          and p.role = 'admin'
      )
    )
  );

-- INSERT: a user can only insert rows they own. The save-to-vault
-- flow uses the service-role key (bypasses RLS) so the INSERT itself
-- is performed as a privileged write from the API route.
create policy "Own data insert"
  on user_notes for insert
  with check (auth.uid() = user_id);

-- UPDATE: a user can only update their own rows. The publish/
-- unpublish endpoint uses the service-role key for the column flip.
create policy "Own data update"
  on user_notes for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- DELETE: a user can only delete their own rows.
create policy "Own data delete"
  on user_notes for delete
  using (auth.uid() = user_id);

-- ============================================================
-- Admin role helper view
-- Returns the admin's user_id. Used by the Vault Bank page to
-- scope "list of published chapters" without leaking the admin
-- id into the client.
-- ============================================================
create or replace view admin_user as
  select id as user_id
  from profiles
  where role = 'admin'
  limit 1;

-- Grant read on the view to authenticated users (aclose users
-- need to query it to know which admin to read shared notes from)
grant select on admin_user to authenticated;
