-- Run this in Supabase SQL Editor to set up your database

-- Study sessions (daily minutes)
create table if not exists study_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  date date not null,
  minutes integer not null default 0,
  created_at timestamptz default now(),
  unique (user_id, date)
);
create index if not exists idx_study_sessions_user on study_sessions(user_id);

-- Quiz scores
create table if not exists quiz_scores (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  date timestamptz not null,
  score integer not null,
  total integer not null,
  net_score integer not null,
  created_at timestamptz default now()
);
create index if not exists idx_quiz_scores_user on quiz_scores(user_id);

-- Test scores
create table if not exists test_scores (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  date timestamptz not null,
  score integer not null,
  total integer not null,
  chapter text not null,
  created_at timestamptz default now()
);
create index if not exists idx_test_scores_user on test_scores(user_id);

-- Activity snapshots
create table if not exists activity_snapshots (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  timestamp text not null,
  type text not null,
  score integer,
  total integer,
  label text,
  items jsonb default '[]',
  created_at timestamptz default now()
);
create index if not exists idx_activity_user on activity_snapshots(user_id);

-- Topic accuracy
create table if not exists topic_accuracy (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  topic text not null,
  correct integer not null default 0,
  total integer not null default 0,
  updated_at timestamptz default now(),
  unique (user_id, topic)
);
create index if not exists idx_topic_accuracy_user on topic_accuracy(user_id);

-- Weak areas
create table if not exists weak_areas (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  topic text not null,
  accuracy numeric(5,2) not null,
  chapter text,
  type text default 'topic',
  created_at timestamptz default now()
);
create index if not exists idx_weak_areas_user on weak_areas(user_id);

-- Enable RLS (Row Level Security)
alter table study_sessions enable row level security;
alter table quiz_scores enable row level security;
alter table test_scores enable row level security;
alter table activity_snapshots enable row level security;
alter table topic_accuracy enable row level security;
alter table weak_areas enable row level security;

-- RLS policies: users can only access their own data
create policy "Users can manage their own study sessions"
  on study_sessions for all using (auth.uid() = user_id);

create policy "Users can manage their own quiz scores"
  on quiz_scores for all using (auth.uid() = user_id);

create policy "Users can manage their own test scores"
  on test_scores for all using (auth.uid() = user_id);

create policy "Users can manage their own activity snapshots"
  on activity_snapshots for all using (auth.uid() = user_id);

create policy "Users can manage their own topic accuracy"
  on topic_accuracy for all using (auth.uid() = user_id);

create policy "Users can manage their own weak areas"
  on weak_areas for all using (auth.uid() = user_id);
