-- ============================================================
-- Run this in Supabase SQL Editor to set up your database
-- ============================================================

-- NOTE: Copy and paste the SECTION for user_notes only
-- into the SQL Editor if you already ran the full schema before.

-- 1. PROFILES
create table if not exists profiles (
  id uuid references auth.users on delete cascade primary key,
  name text default '',
  username text,
  bio text default '',
  avatar_url text default '',
  instagram text default '',
  twitter text default '',
  github text default '',
  website text default '',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
create unique index if not exists idx_profiles_username on profiles(username) where username is not null;

-- 2. STUDY SESSIONS (daily minutes)
create table if not exists study_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  date date not null,
  minutes integer not null default 0,
  created_at timestamptz default now(),
  unique (user_id, date)
);
create index if not exists idx_study_sessions_user on study_sessions(user_id);

-- 3. QUIZ SCORES
create table if not exists quiz_scores (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  date timestamptz not null,
  score integer not null,
  total integer not null,
  net_score integer not null,
  created_at timestamptz default now(),
  unique (user_id, date)
);
create index if not exists idx_quiz_scores_user on quiz_scores(user_id);

-- 4. TEST SCORES
create table if not exists test_scores (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  date timestamptz not null,
  score integer not null,
  total integer not null,
  chapter text not null,
  created_at timestamptz default now(),
  unique (user_id, date, chapter)
);
create index if not exists idx_test_scores_user on test_scores(user_id);

-- 5. ACTIVITY SNAPSHOTS
create table if not exists activity_snapshots (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  timestamp text not null,
  type text not null,
  score integer,
  total integer,
  label text,
  items jsonb default '[]',
  created_at timestamptz default now(),
  unique (user_id, timestamp, type)
);
create index if not exists idx_activity_user on activity_snapshots(user_id);

-- 6. TOPIC ACCURACY
create table if not exists topic_accuracy (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  topic text not null,
  correct integer not null default 0,
  total integer not null default 0,
  updated_at timestamptz default now(),
  unique (user_id, topic)
);
create index if not exists idx_topic_accuracy_user on topic_accuracy(user_id);

-- 7. WEAK AREAS
create table if not exists weak_areas (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  topic text not null,
  accuracy numeric(5,2) not null,
  chapter text,
  type text default 'topic',
  created_at timestamptz default now()
);
create index if not exists idx_weak_areas_user on weak_areas(user_id);

-- 8. CHAPTER PROGRESS
create table if not exists chapter_progress (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  chapter text not null,
  subject text not null,
  completed_topics integer default 0,
  total_topics integer default 0,
  questions_attempted integer default 0,
  questions_correct integer default 0,
  flashcards_reviewed integer default 0,
  flashcards_mastered integer default 0,
  last_studied_at timestamptz,
  unique (user_id, chapter, subject)
);
create index if not exists idx_chapter_progress_user on chapter_progress(user_id);

-- 9. USER POINTS (for leaderboard)
create table if not exists user_points (
  user_id uuid references auth.users on delete cascade primary key,
  points integer not null default 0,
  updated_at timestamptz default now()
);

-- 10. USER NOTES (private per-user vault storage)
-- Each note preserves the file path + content so the parser/layout works unchanged.
create table if not exists user_notes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  chapter text not null,
  subject text not null default '',
  path text not null,
  title text not null,
  content text not null,
  tags text[] default '{}',
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (user_id, path)
);
create index if not exists idx_user_notes_user on user_notes(user_id);

-- 11. CHAT MESSAGES (AI Tutor conversations)
create table if not exists chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  session_id uuid not null,
  role text not null,
  content text not null,
  created_at timestamptz default now()
);
create index if not exists idx_chat_messages_session on chat_messages(user_id, session_id);

-- 12. STUDY STREAKS
create table if not exists study_streaks (
  user_id uuid references auth.users on delete cascade primary key,
  current_streak integer not null default 0,
  longest_streak integer not null default 0,
  last_study_date date,
  updated_at timestamptz default now()
);

-- ============================================================
-- RLS POLICIES
-- ============================================================
alter table profiles enable row level security;
alter table study_sessions enable row level security;
alter table quiz_scores enable row level security;
alter table test_scores enable row level security;
alter table activity_snapshots enable row level security;
alter table topic_accuracy enable row level security;
alter table weak_areas enable row level security;
alter table chapter_progress enable row level security;
alter table user_points enable row level security;
alter table user_notes enable row level security;
alter table chat_messages enable row level security;
alter table study_streaks enable row level security;

-- All tables: users can only access their own data
drop policy if exists "Own data only" on profiles;
create policy "Own data only" on profiles for all using (auth.uid() = id);
drop policy if exists "Own data only" on study_sessions;
create policy "Own data only" on study_sessions for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on quiz_scores;
create policy "Own data only" on quiz_scores for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on test_scores;
create policy "Own data only" on test_scores for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on activity_snapshots;
create policy "Own data only" on activity_snapshots for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on topic_accuracy;
create policy "Own data only" on topic_accuracy for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on weak_areas;
create policy "Own data only" on weak_areas for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on chapter_progress;
create policy "Own data only" on chapter_progress for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on user_points;
create policy "Own data only" on user_points for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on user_notes;
create policy "Own data only" on user_notes for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on chat_messages;
create policy "Own data only" on chat_messages for all using (auth.uid() = user_id);
drop policy if exists "Own data only" on study_streaks;
create policy "Own data only" on study_streaks for all using (auth.uid() = user_id);

-- Public can read usernames and points for leaderboard
drop policy if exists "Public read leaderboard" on profiles;
create policy "Public read leaderboard" on profiles for select using (true);
drop policy if exists "Public read points" on user_points;
create policy "Public read points" on user_points for select using (true);
