-- ============================================================
-- Migration 003: ROC2 Backup Logs Table
-- Run this in Supabase SQL Editor after migration-002
-- ============================================================

-- 19. BACKUP LOGS (ROC2 backup status tracking)
create table if not exists backup_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete set null,
  type text not null default 'manual',
  status text not null default 'completed',
  size_bytes bigint default 0,
  duration_ms integer default 0,
  message text default '',
  metadata jsonb not null default '{}',
  created_at timestamptz default now()
);

-- Indexes for latest-backup queries
create index if not exists idx_backup_logs_created
  on backup_logs(created_at desc);

create index if not exists idx_backup_logs_type
  on backup_logs(type, created_at desc);

-- RLS: users can see their own backups, admins can see all
alter table backup_logs enable row level security;

drop policy if exists "Users read own backups" on backup_logs;
create policy "Users read own backups"
  on backup_logs for select
  using (auth.uid() = user_id);

drop policy if exists "Admins read all backups" on backup_logs;
create policy "Admins read all backups"
  on backup_logs for select
  using (
    exists (select 1 from profiles where id = auth.uid() and role = 'admin')
  );

drop policy if exists "Users insert own backups" on backup_logs;
create policy "Users insert own backups"
  on backup_logs for insert
  with check (auth.uid() = user_id);

-- Allow service_role inserts
alter table backup_logs force row level security;

-- Analyze
analyze backup_logs;
