-- ============================================================
-- Migration 002: ROC2 Server Logs Table
-- Run this in Supabase SQL Editor after migration-001
-- ============================================================

-- 18. SERVER LOGS (ROC2 observability — request lifecycle logging)
create table if not exists server_logs (
  id bigint generated by default as identity primary key,
  route text not null,
  user_id uuid references auth.users on delete set null,
  method text not null default 'GET',
  level text not null default 'info',
  status_code integer not null default 0,
  duration_ms integer not null default 0,
  message text,
  error_message text,
  metadata jsonb not null default '{}',
  created_at timestamptz default now()
);

-- Indexes for ROC2 dashboard queries
create index if not exists idx_server_logs_created
  on server_logs(created_at desc);

create index if not exists idx_server_logs_level
  on server_logs(created_at desc, level);

create index if not exists idx_server_logs_user
  on server_logs(user_id, created_at desc);

create index if not exists idx_server_logs_route
  on server_logs(route, created_at desc);

-- BRIN index for time-series range scans
create index if not exists idx_server_logs_brin
  on server_logs using BRIN (created_at)
  with (pages_per_range = 32);

-- RLS: users can see their own logs, admins can see all
alter table server_logs enable row level security;

drop policy if exists "Users read own logs" on server_logs;
create policy "Users read own logs"
  on server_logs for select
  using (auth.uid() = user_id);

drop policy if exists "Admins read all logs" on server_logs;
create policy "Admins read all logs"
  on server_logs for select
  using (
    exists (select 1 from profiles where id = auth.uid() and role = 'admin')
  );

-- Authenticated users can insert their own logs (Edge Functions use service_role which bypasses RLS)
drop policy if exists "Users insert own logs" on server_logs;
create policy "Users insert own logs"
  on server_logs for insert
  with check (auth.uid() = user_id);

-- Allow service_role (used by createClient()) to insert for any user
alter table server_logs force row level security;

-- Analyze
analyze server_logs;
