/**
 * ROC2 Migration Runner
 *
 * POST /api/roc2/migrate — runs pending ROC2 migrations
 * GET  /api/roc2/migrate — lists available migrations
 *
 * Requires SUPABASE_PROJECT_REF + SUPABASE_SERVICE_ROLE_KEY env vars
 * for automatic SQL execution via the Supabase Management API.
 *
 * Without those vars, provides the SQL text for manual copy-paste
 * into the Supabase SQL Editor.
 *
 * Security: restricted to admin users.
 *
 * ── Setup ──────────────────────────────────────────────────────
 * 1. Go to supabase.com/dashboard → Project Settings → API
 * 2. Copy your Project Reference → set SUPABASE_PROJECT_REF
 * 3. Copy your service_role key → set SUPABASE_SERVICE_ROLE_KEY
 * 4. POST to this endpoint to run migrations automatically
 *
 * ── Manual alternative ─────────────────────────────────────────
 * Open Supabase SQL Editor and paste the SQL from the GET response.
 */

import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { logRequest } from "@/lib/server-log";

const MIGRATIONS = [
  {
    name: "002-server-logs",
    file: "src/lib/supabase/migration-002-server-logs.sql",
    sql: `
-- 18. SERVER LOGS (ROC2 observability)
create table if not exists server_logs (
  id bigint generated by default as identity primary key,
  route text not null,
  user_id uuid references auth.users on delete set null,
  method text not null default 'GET',
  level text not null default 'info',
  status_code integer not null default 0,
  duration_ms integer not null default 0,
  message text,
  error_message text,
  metadata jsonb not null default '{}',
  created_at timestamptz default now()
);

create index if not exists idx_server_logs_created on server_logs(created_at desc);
create index if not exists idx_server_logs_level on server_logs(created_at desc, level);
create index if not exists idx_server_logs_user on server_logs(user_id, created_at desc);
create index if not exists idx_server_logs_route on server_logs(route, created_at desc);
create index if not exists idx_server_logs_brin on server_logs using BRIN (created_at) with (pages_per_range = 32);

alter table server_logs enable row level security;
drop policy if exists "Users read own logs" on server_logs;
create policy "Users read own logs" on server_logs for select using (auth.uid() = user_id);
drop policy if exists "Admins read all logs" on server_logs;
create policy "Admins read all logs" on server_logs for select using (
  exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);
drop policy if exists "Users insert own logs" on server_logs;
create policy "Users insert own logs" on server_logs for insert with check (auth.uid() = user_id);
alter table server_logs force row level security;
analyze server_logs;
    `.trim(),
  },
  {
    name: "003-backup-logs",
    file: "src/lib/supabase/migration-003-backup-logs.sql",
    sql: `
-- 19. BACKUP LOGS (ROC2 backup status tracking)
create table if not exists backup_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete set null,
  type text not null default 'manual',
  status text not null default 'completed',
  size_bytes bigint default 0,
  duration_ms integer default 0,
  message text default '',
  metadata jsonb not null default '{}',
  created_at timestamptz default now()
);

create index if not exists idx_backup_logs_created on backup_logs(created_at desc);
create index if not exists idx_backup_logs_type on backup_logs(type, created_at desc);

alter table backup_logs enable row level security;
drop policy if exists "Users read own backups" on backup_logs;
create policy "Users read own backups" on backup_logs for select using (auth.uid() = user_id);
drop policy if exists "Admins read all backups" on backup_logs;
create policy "Admins read all backups" on backup_logs for select using (
  exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);
drop policy if exists "Users insert own backups" on backup_logs;
create policy "Users insert own backups" on backup_logs for insert with check (auth.uid() = user_id);
alter table backup_logs force row level security;
analyze backup_logs;
    `.trim(),
  },
];

interface MigrationResult {
  name: string;
  success: boolean;
  error?: string;
}

export async function POST(request: Request) {
  const log = logRequest("POST /api/roc2/migrate", null);

  try {
    if (!process.env.NEXT_PUBLIC_SUPABASE_URL) {
      return NextResponse.json({ error: "supabase_not_configured" }, { status: 501 });
    }

    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return NextResponse.json({ error: "unauthorized" }, { status: 401 });
    log.setMeta("userId", user.id);

    const { data: profile } = await supabase
      .from("profiles")
      .select("role")
      .eq("id", user.id)
      .maybeSingle();
    if (profile?.role !== "admin") {
      return NextResponse.json({ error: "forbidden", message: "Admin access required" }, { status: 403 });
    }

    const projectRef = process.env.SUPABASE_PROJECT_REF;
    const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

    if (!projectRef || !serviceKey) {
      // No Management API — return SQL for manual execution
      return NextResponse.json({
        migrated: false,
        requiresManual: true,
        message: "Set SUPABASE_PROJECT_REF and SUPABASE_SERVICE_ROLE_KEY for auto-execution, or copy the SQL below into Supabase SQL Editor.",
        migrations: MIGRATIONS.map((m) => ({ name: m.name, sql: m.sql })),
      });
    }

    const results: MigrationResult[] = [];

    for (const migration of MIGRATIONS) {
      try {
        const res = await fetch(
          `https://api.supabase.com/v1/projects/${projectRef}/sql`,
          {
            method: "POST",
            headers: {
              "Authorization": `Bearer ${serviceKey}`,
              "Content-Type": "application/json",
            },
            body: JSON.stringify({ query: migration.sql }),
          }
        );

        if (!res.ok) {
          const errBody = await res.text().catch(() => "unknown");
          results.push({
            name: migration.name,
            success: false,
            error: `API ${res.status}: ${errBody.slice(0, 300)}`,
          });
        } else {
          results.push({ name: migration.name, success: true });
        }
      } catch (err) {
        results.push({
          name: migration.name,
          success: false,
          error: err instanceof Error ? err.message : "unknown_error",
        });
      }
    }

    const allSuccess = results.every((r) => r.success);
    const failedCount = results.filter((r) => !r.success).length;

    log.setMeta("migrations", results.map((r) => `${r.name}=${r.success ? "ok" : "fail"}`).join(","));

    if (allSuccess) {
      await log.success(200, `All ${results.length} migrations completed`);
      return NextResponse.json({ migrated: true, results });
    }

    await log.warn(500, `${failedCount}/${results.length} migrations failed`);
    return NextResponse.json({ migrated: false, results }, { status: 500 });
  } catch (err) {
    await log.error("migration_failed", err);
    return NextResponse.json(
      { error: err instanceof Error ? err.message : "unknown_error" },
      { status: 500 }
    );
  }
}

export async function GET() {
  return NextResponse.json({
    migrations: MIGRATIONS.map((m) => ({
      name: m.name,
      file: m.file,
      sql: m.sql,
    })),
    autoExecAvailable: !!(process.env.SUPABASE_PROJECT_REF && process.env.SUPABASE_SERVICE_ROLE_KEY),
    instructions: "POST to run via Management API, or copy SQL from any response and paste into Supabase SQL Editor.",
  });
}
